Address accessibility issues on /signup
Fixes issues from the following report:

*** Begin accessibility audit results ***
An accessibility audit found
Errors:
Error: AX_TEXT_01 (Controls and media elements should have labels)
failed on the following element:
 #mc_embed_signup_scroll > DIV:nth-of-type(6) > INPUT
See
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_01
for more information.

Warnings:
Warning: AX_COLOR_01 (Text elements should have a reasonable contrast
ratio) failed on the following element:
 #mc_embed_signup_scroll > .indicates-required > .asterisk
See
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_color_01
for more information.

*** End accessibility audit results ***